### PR TITLE
Change: restful interface GET uses JSON to serialize data

### PR DESCRIPTION
**Pull request by IYism**

### CODE REVIEW

**Comment by Frodox** [comment]
:heart:

**Comment by Frodox** [comment]
@yzprofile could you take a look, please ?

**Comment by yzprofile** [comment]
thanks for your efforts.

i don't think use json is a good idea.

**Comment by Frodox** [comment]
@yzprofile why...?
JSON - is only comfortable format to use from cli/any program interface.

Why Do you think it is better to parse plain/text..?

**Pull request closed without merging**
